steps:
  # 0. Create Artifact Registry Repo if not exists
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe $_REPO_NAME --location=$_REGION > /dev/null 2>&1; then
          gcloud artifacts repositories create $_REPO_NAME --repository-format=docker --location=$_REGION --description="Docker repository for Tech Influencer Agent"
        fi
    id: 'Create Repo'

  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA', '.']
    id: 'Build'

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA']
    id: 'Push'

  # 3. Update Cloud Run Job (Create if not exists)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud run jobs describe $_JOB_NAME --region $_REGION > /dev/null 2>&1
        if [ $? -eq 0 ]; then
          gcloud run jobs update $_JOB_NAME \
            --image $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA \
            --region $_REGION \
            --service-account phantom-influencer-sa@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars PROJECT_ID=$PROJECT_ID,REGION=$_REGION,BUDGET_MODE=$_BUDGET_MODE
        else
          gcloud run jobs create $_JOB_NAME \
            --image $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA \
            --region $_REGION \
            --service-account phantom-influencer-sa@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars PROJECT_ID=$PROJECT_ID,REGION=$_REGION,BUDGET_MODE=$_BUDGET_MODE \
            --max-retries 1 \
            --task-timeout 10m
        fi
    id: 'Deploy'

substitutions:
  _REGION: us-central1
  _REPO_NAME: phantom-repo
  _IMAGE_NAME: phantom-influencer
  _JOB_NAME: phantom-influencer-job
  _BUDGET_MODE: "False"

options:
  logging: CLOUD_LOGGING_ONLY
